name: 'test'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        kind: [pip]
        python: ['3.11']
        include:
          - os: macos-latest
            kind: mamba
            python: '3.8'
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
        if: ${{ matrix.kind == 'pip' }}
      - run: |
          wget -q -O tools/get_minimal_commands.sh https://raw.githubusercontent.com/mne-tools/mne-python/main/tools/get_minimal_commands.sh
          source ./tools/get_minimal_commands.sh
        if: ${{ ! startswith(matrix.os, 'windows') }}
        name: 'Install neuromag2ft'
      - run: neuromag2ft --version
        if: ${{ ! startswith(matrix.os, 'windows') }}
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt git+https://github.com/mne-tools/mne-python -ve .
      - run: mne sys_info
      - run: python -c "import mne; print(mne.datasets.testing.data_path(verbose=True))"
        name: 'Get test data'
      - run: pytest -vv mne_realtime
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
