name: 'linux / pip'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 4 * * 0"

jobs:
  job:
    name: 'py3.11'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        name: 'Setup python'
      - run: |
          wget -q -O tools/get_minimal_commands.sh https://raw.githubusercontent.com/mne-tools/mne-python/main/tools/get_minimal_commands.sh
          source ./tools/get_minimal_commands.sh
        name: 'Install neuromag2ft'
      - run: neuromag2ft --version
      - run: ./tools/pip_dependencies.sh
      - run: pip install --upgrade git+https://github.com/mne-tools/mne-python.git
      - run: mne sys_info
      - run: python -c "import mne; print(mne.datasets.testing.data_path(verbose=True))"
        name: 'Get test data'
      - run: pytest -vv mne_realtime
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
