name: 'macos / pip'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: 'py3.6'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    env:
      PYTHON_VERSION: '3.7'
      MNE_LOGGING_LEVEL: 'warning'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        name: 'Setup python'
      - shell: bash -el {0}
        run: ./tools/pip_dependencies.sh
        name: 'Install MNE-Realtime'
      - shell: bash -el {0}
        run: python -c "import mne; print(mne.datasets.testing.data_path(verbose=True))"
        name: 'Get test data'
      - shell: bash -el {0}
        run: pytest mne_realtime
        name: 'Run tests'
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
