name: 'macos / conda'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 4 * * 0"

jobs:
  job:
    name: 'py3.8'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8'
          auto-update-conda: true
          environment-file: 'environment.yml'
          activate-environment: 'mne_realtime'
        name: 'Setup conda'
      - run: ./tools/pip_dependencies.sh
      - run: mne sys_info
      - run: python -c "import mne; print(mne.datasets.testing.data_path(verbose=True))"
        name: 'Get test data'
      - run: pytest mne_realtime
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
